# Generated by Django 5.0.7 on 2024-09-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_social_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_social_user',
            field=models.BooleanField(default=False),
        ),
    ]
