# Generated by Django 5.0.7 on 2024-09-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_social_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_social_user',
            new_name='is_no_social_user',
        ),
    ]
