# Generated by Django 5.0.7 on 2024-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_social_user_user_is_no_social_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_no_social_user',
            field=models.BooleanField(default=True),
        ),
    ]
