# Generated by Django 5.0.7 on 2024-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_no_social_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_no_social_user',
            field=models.BooleanField(default=False),
        ),
    ]
