# Generated by Django 5.0.7 on 2024-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=255, verbose_name='Telegram Token')),
                ('tg_chat_id', models.CharField(max_length=255, verbose_name='Telegram Chat ID')),
                ('message', models.TextField()),
            ],
        ),
    ]
