name: Pull Request Check

on:
  push:
    branches:
      - master

env:
  USE_SQLITE: true

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy to the Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check code style
        run: flake8
#      - name: Run migrations
#        run: python manage.py migrate
      - name: Generate Google config
        run: echo "{\"type\": \"service_account\", \"project_id\": \"postcards-shop-436417\",\"private_key_id\": \"\", \"private_key\": \"\", \"client_email\": \"postcards@postcards-shop-436417.iam.gserviceaccount.com\",\"client_id\": \"106423772165774447797\", \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\", \"token_uri\": \"https://oauth2.googleapis.com/token\", \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\", \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/postcards%40postcards-shop-436417.iam.gserviceaccount.com\", \"universe_domain\": \"googleapis.com\"}" > ../google_sheet/service-account.json
      - name: Run tests
        run: coverage run manage.py test
#      - name: Generate coverage report
#        run: coverage report --fail-under=80
      - name: deploy on push
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYHOST }}
          username: ${{ secrets.DEPLOYLOGIN }}
          key: ${{ secrets.DEPLOYKEY }}
          port: 22
          script: ${{ github.event.repository.name }}

