# Generated by Django 5.0.7 on 2024-08-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='created_at',
            new_name='created_timestamp',
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
