# Generated by Django 5.0.7 on 2024-08-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_created_at_basket_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Листівку', 'verbose_name_plural': 'Листівки'},
        ),
    ]
