# Generated by Django 5.0.7 on 2024-08-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_price_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
