# Generated by Django 5.0.7 on 2024-08-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stripe_product_price_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_product_price_1',
            new_name='stripe_product_price_id',
        ),
    ]
